services:
  - type: web
    name: fd_recom
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: SPOONACULAR_API_KEYS
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: fd_recom
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
