services:
  - type: web
    name: fd_recom
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: SPOONACULAR_API_KEYS
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d18103ogjchc73f8kor0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: fd_recomdb
      - key: DB_USERNAME
        value: fd_recomdb_user
      - key: DB_PASSWORD
        value: dd44fP2Qlrkmb15DzBUB76Kl5QSF1NGB
